import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { Mouse } from "@/components/mouse";
import { ViewTransitions } from "next-view-transitions";
import { Link } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className="">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="layer">
            <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
              <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start ">
                {/* <Hello />  */}
                {children}
                {/* <Mouse /> */}
              </main>
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </ViewTransitions>
  );
}
